services:
  app:
    build: .
    container_name: fastapi_app
    env_file: .env.prod
    ports:
      - "8000:8000"
    networks:
      - mynetwork
    environment:
      - PYTHONPATH=/app

networks:
  mynetwork:

volumes:
  db_data:
