services:
  nginx:
    image: nginx:latest
    container_name: nginx
    env_file: .env.prod
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      app:
        condition: service_healthy

  app:
    build: .
    container_name: fastapi_app
    env_file: .env.prod
    ports:
      - "8000:8000"
    networks:
      - mynetwork
    environment:
      - PYTHONPATH=/app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/docs"]
      interval: 30s
      retries: 3
      start_period: 5s
      timeout: 10s

networks:
  mynetwork:

volumes:
  db_data:
